[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "github.com/gardener/gardener"