[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

[[constraint]]
  name = "github.com/gardener/gardener"
  version = "^0.13.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.1"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"